name = "Horrorpack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f95f090e01641563c1d013ea13f8ce60a35b13e3b7cbce688b4d10c6246ab329"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
