name = "The Aether"
filename = "aether-1.12.2-v1.5.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3280/119/aether-1.12.2-v1.5.3.2.jar"
hash-format = "murmur2"
hash = "1704651515"

[update]
[update.curseforge]
file-id = 3280119
project-id = 255308
