name = "Armor Chroma"
filename = "armorchroma-1.12.2-1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2666/633/armorchroma-1.12.2-1.4.jar"
hash-format = "murmur2"
hash = "725752111"

[update]
[update.curseforge]
file-id = 2666633
project-id = 238534
