name = "Extra Spells (Electroblob's Wizardry)"
filename = "ExtraSpells-1.12.2-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3091/628/ExtraSpells-1.12.2-1.2.0.jar"
hash-format = "murmur2"
hash = "1995138255"

[update]
[update.curseforge]
file-id = 3091628
project-id = 310745
