name = "Foam​Fix"
filename = "foamfix-0.10.14-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3327/893/foamfix-0.10.14-1.12.2.jar"
hash-format = "murmur2"
hash = "2480667074"

[update]
[update.curseforge]
file-id = 3327893
project-id = 278494
