name = "Mixin 0.7-0.8 Compatibility"
filename = "[___MixinCompat-0.8___].jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3045/381/[___MixinCompat-0.8___].jar"
hash-format = "murmur2"
hash = "89892035"

[update]
[update.curseforge]
file-id = 3045381
project-id = 405327
