name = "Mo' Bends"
filename = "MoBends_1.12.2-1.2.1-19.12.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3573/346/MoBends_1.12.2-1.2.1-19.12.21.jar"
hash-format = "murmur2"
hash = "1249426856"

[update]
[update.curseforge]
file-id = 3573346
project-id = 231347
